### ISSUE TITLE
Missing GPL source for fip.bin

### ISSUE THREAD

**Issue by xypron** [sophgo/bootloader-riscv#4]
It seems that fip.bin contains different pieces of software with different licenses:

* ARM Trusted Firmware (BSD-3-Clause license)
* U-Boot 2022.10 (GPL v2 license)

The Gnu Public License of U-Boot requires providing the source code of derived works. fp.bin is such a derived work.

The BSD 3 license of ARM Trusted Firmware allows binary only distribution.

To comply with the U-Boot license, please, consider either providing all code to create fp.bin or separating the two software pieces and providing the U-Boot in source form and TF-A in binary form.

Publishing your U-Boot source will provide a starting point for adding Sophgo specific parts to the mainline U-Boot and thereby to ensure long term support.

**Comment by 605925527** [comment]
Thanks. It has been updated to remove uboot.
